apiVersion: v1
kind: Secret
metadata:
  name: storage-creds
  labels:
    heritage: drycc
type: Opaque
data:
  accesskey: {{ include "common.secrets.lookup" (dict "secret" "storage-creds" "key" "accesskey" "defaultValue" (default (randAlphaNum 32) .Values.accesskey) "context" $) }}
  secretkey: {{ include "common.secrets.lookup" (dict "secret" "storage-creds" "key" "secretkey" "defaultValue" (default (randAlphaNum 32) .Values.secretkey) "context" $) }}
